# Generated by Django 5.0.2 on 2024-03-01 15:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('empleado', '0003_cargo_ficha_cargo_perfil_alter_empleado_cargo_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cargo',
            old_name='ficha',
            new_name='codigo',
        ),
        migrations.AddField(
            model_name='empleado',
            name='ficha',
            field=models.CharField(default=1, max_length=15),
            preserve_default=False,
        ),
    ]
