# Generated by Django 5.0.1 on 2024-03-14 20:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('empleado', '0004_rename_ficha_cargo_codigo_empleado_ficha'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cargo',
            options={'verbose_name': 'cargo', 'verbose_name_plural': 'cargos'},
        ),
        migrations.AlterModelOptions(
            name='empleado',
            options={'verbose_name': 'empleado', 'verbose_name_plural': 'empleados'},
        ),
        migrations.AddField(
            model_name='empleado',
            name='departamento',
            field=models.CharField(default='recursos_humanos', max_length=15),
        ),
        migrations.AlterField(
            model_name='cargo',
            name='codigo',
            field=models.CharField(max_length=15, unique=True),
        ),
        migrations.AlterField(
            model_name='empleado',
            name='ficha',
            field=models.CharField(max_length=15, unique=True),
        ),
    ]
